config/routes.rb
Finance::Application.routes.draw do

  resources :pagamentos

  resources :metodo_de_pagamentos

  resources :categoria_do_pagamentos

  resources :tipo_do_pagamentos

  resources :recebimentos
  
  match "consulta_data", :to => "recebimentos#consulta_data", :as => "consulta_data"

  resources :forma_de_recebimentos

  resources :categoria_do_recebimentos

  resources :tipo_de_recebimentos

  resources :sessions

	match "profile", :to => "users#show", :as => "profile"
	match "logout", :to => "sessions#destroy", :as => "logout"
	match "login", :to => "sessions#new", :as => "login"
	match "admin", :to => "users#admin", :as => "admin"

	resources :users
	

   root :to => "sessions#new"

end

app/models/tipo_do_pagamento.rb
class TipoDoPagamento < ActiveRecord::Base
  has_many :pagamentos
  belongs_to :users

  validates :nome_do_tipo, :presence => true
	validates :descricao_do_tipo, :presence => true
end

app/controllers/tipo_do_pagamentos_controller.rb
class TipoDoPagamentosController < ApplicationController
  # GET /tipo_do_pagamentos
  # GET /tipo_do_pagamentos.xml
  def index
    @tipo_do_pagamentos = TipoDoPagamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tipo_do_pagamentos }
    end
  end

  # GET /tipo_do_pagamentos/1
  # GET /tipo_do_pagamentos/1.xml
  def show
    @tipo_do_pagamento = TipoDoPagamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tipo_do_pagamento }
    end
  end

  # GET /tipo_do_pagamentos/new
  # GET /tipo_do_pagamentos/new.xml
  def new
    @tipo_do_pagamento = TipoDoPagamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tipo_do_pagamento }
    end
  end

  # GET /tipo_do_pagamentos/1/edit
  def edit
    @tipo_do_pagamento = TipoDoPagamento.find(params[:id])
  end

  # POST /tipo_do_pagamentos
  # POST /tipo_do_pagamentos.xml
  def create
    @tipo_do_pagamento = TipoDoPagamento.new(params[:tipo_do_pagamento])

    respond_to do |format|
      if @tipo_do_pagamento.save
        format.html { redirect_to(@tipo_do_pagamento, :notice => 'Tipo do pagamento was successfully created.') }
        format.xml  { render :xml => @tipo_do_pagamento, :status => :created, :location => @tipo_do_pagamento }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tipo_do_pagamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tipo_do_pagamentos/1
  # PUT /tipo_do_pagamentos/1.xml
  def update
    @tipo_do_pagamento = TipoDoPagamento.find(params[:id])

    respond_to do |format|
      if @tipo_do_pagamento.update_attributes(params[:tipo_do_pagamento])
        format.html { redirect_to(@tipo_do_pagamento, :notice => 'Tipo do pagamento was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tipo_do_pagamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_do_pagamentos/1
  # DELETE /tipo_do_pagamentos/1.xml
  def destroy
    @tipo_do_pagamento = TipoDoPagamento.find(params[:id])
    @tipo_do_pagamento.destroy

    respond_to do |format|
      format.html { redirect_to(tipo_do_pagamentos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tipo_do_pagamentos_helper.rb
module TipoDoPagamentosHelper
end

app/views/tipo_do_pagamentos/_form.html.erb
<%= form_for(@tipo_do_pagamento) do |f| %>

	<% if @tipo_do_pagamento.errors.any? %>
		<div class="message errormsg" style="display: block; ">
		Não foi possível salvar esse tipo de pagamento</p><br/><br/>
		<% @tipo_do_pagamento.errors.full_messages.each do |msg| %>
		<ul>
		<li><%= msg %></li>
		</ul>
		<% end %>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :nome_do_tipo, "Nome" %><br />
		<%= f.text_field :nome_do_tipo, :class => "text small"  %>
	</div><br/>
	
	<div class="field">
		<%= f.label :descricao_do_tipo, "Descrição" %><br />
		<%= f.text_field :descricao_do_tipo, :class => "text small"  %>
	</div><br/>
		<%= f.submit 'Cadastrar', :class => 'submit mid' %>
<% end %>

app/views/tipo_do_pagamentos/edit.html.erb
<div class="block">

	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		<h2>Editar Tipo do Pagamento</h2>
	</div>

	<div class="block_content">
	<%= render 'form' %>

<br/>
		<hr>
		<%= link_to 'Show', @tipo_do_pagamento %> | <%= link_to 'Back', tipo_do_pagamentos_path %>

	</div>

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>

app/views/tipo_do_pagamentos/index.html.erb
<div class="block">

	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
	<h2>Lista de Tipos do Pagamentos</h2>
		<div class="tableactions" style="text-align: center">
		<%= link_to image_tag('icones/Add.png', :title => "Cadastrar"), new_tipo_do_pagamento_path %>
		</div>
	</div>

<div class="block_content">
	<table cellpadding="0" cellspacing="0" width="100%" class="sortable">

		<tr>
			<th>Nome</th>
			<th>Descrição</th>
		</tr>

	<% @tipo_do_pagamentos.each do |tipo_do_pagamento| %>
		<tr>
		  <td><%= tipo_do_pagamento.nome_do_tipo %></td>
		  <td><%= tipo_do_pagamento.descricao_do_tipo %></td>


			<td><%= link_to image_tag('icones/Search.png', :title => "Visualizar"), tipo_do_pagamento %></td>
			<td><%= link_to image_tag('icones/Modify.png', :title => "Editar"), edit_tipo_do_pagamento_path(tipo_do_pagamento) %></td>
			<td><%= link_to image_tag('icones/Delete.png', :title => "Deletar"), tipo_do_pagamento, :confirm => 'Are you sure?', :method => :delete %></td>

		</tr>

	<% end %>
</table>

	<div class="pagination right">

	</div>

</div>

<div class="bendl"></div>
	<div class="bendr"></div>

	</div>

app/views/tipo_do_pagamentos/new.html.erb
<div class="block">

	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		<h2>Cadastrar Tipo do Pagamento</h2>
	</div>

	<div class="block_content">
	<%= render 'form' %>

<br/>
		<hr>
		<%= link_to 'Back', tipo_do_pagamentos_path %>

	</div>

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>

app/views/tipo_do_pagamentos/show.html.erb
<p id="notice"><%= notice %></p>



<div class="block">

	<div class="block_head">
			<div class="bheadl"></div>
			<div class="bheadr"></div>

	<h2>Resumo do Pagamento</h2>
	</div>

	<div class="block_content">

	<table cellpadding="0" cellspacing="0" width="100%" class="sortable">

	<tr>
		<th>Nome</th>
		<th>Descrição</th>
	</tr>

	<tr>
		<td><%= @tipo_do_pagamento.nome_do_tipo %></td>
		<td><%= @tipo_do_pagamento.descricao_do_tipo %></td>
	</tr>
</table>

<div class="tableactions">
			<%= link_to 'Edit', edit_tipo_do_pagamento_path(@tipo_do_pagamento) %> |
			<%= link_to 'Back', tipo_do_pagamentos_path %>
		</div>

		<div class="pagination right">

		</div>

	</div>

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>