config/routes.rb
Finance::Application.routes.draw do

  resources :pagamentos

  resources :metodo_de_pagamentos

  resources :categoria_do_pagamentos

  resources :tipo_do_pagamentos

  resources :recebimentos
  
  match "consulta_data", :to => "recebimentos#consulta_data", :as => "consulta_data"

  resources :forma_de_recebimentos

  resources :categoria_do_recebimentos

  resources :tipo_de_recebimentos

  resources :sessions

	match "profile", :to => "users#show", :as => "profile"
	match "logout", :to => "sessions#destroy", :as => "logout"
	match "login", :to => "sessions#new", :as => "login"
	match "admin", :to => "users#admin", :as => "admin"

	resources :users
	

   root :to => "sessions#new"

end

app/models/categoria_do_pagamento.rb
class CategoriaDoPagamento < ActiveRecord::Base
has_many :pagamentos
belongs_to :users

  validates :nome_da_categoria, :presence => true
  validates :descricao_da_categoria, :presence => true

end

app/controllers/categoria_do_pagamentos_controller.rb
class CategoriaDoPagamentosController < ApplicationController
  # GET /categoria_do_pagamentos
  # GET /categoria_do_pagamentos.xml
  def index
    @categoria_do_pagamentos = CategoriaDoPagamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categoria_do_pagamentos }
    end
  end

  # GET /categoria_do_pagamentos/1
  # GET /categoria_do_pagamentos/1.xml
  def show
    @categoria_do_pagamento = CategoriaDoPagamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @categoria_do_pagamento }
    end
  end

  # GET /categoria_do_pagamentos/new
  # GET /categoria_do_pagamentos/new.xml
  def new
    @categoria_do_pagamento = CategoriaDoPagamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @categoria_do_pagamento }
    end
  end

  # GET /categoria_do_pagamentos/1/edit
  def edit
    @categoria_do_pagamento = CategoriaDoPagamento.find(params[:id])
  end

  # POST /categoria_do_pagamentos
  # POST /categoria_do_pagamentos.xml
  def create
    @categoria_do_pagamento = CategoriaDoPagamento.new(params[:categoria_do_pagamento])

    respond_to do |format|
      if @categoria_do_pagamento.save
        format.html { redirect_to(@categoria_do_pagamento, :notice => 'Categoria do pagamento was successfully created.') }
        format.xml  { render :xml => @categoria_do_pagamento, :status => :created, :location => @categoria_do_pagamento }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @categoria_do_pagamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categoria_do_pagamentos/1
  # PUT /categoria_do_pagamentos/1.xml
  def update
    @categoria_do_pagamento = CategoriaDoPagamento.find(params[:id])

    respond_to do |format|
      if @categoria_do_pagamento.update_attributes(params[:categoria_do_pagamento])
        format.html { redirect_to(@categoria_do_pagamento, :notice => 'Categoria do pagamento was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @categoria_do_pagamento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria_do_pagamentos/1
  # DELETE /categoria_do_pagamentos/1.xml
  def destroy
    @categoria_do_pagamento = CategoriaDoPagamento.find(params[:id])
    @categoria_do_pagamento.destroy

    respond_to do |format|
      format.html { redirect_to(categoria_do_pagamentos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/categoria_do_pagamentos_helper.rb
module CategoriaDoPagamentosHelper
end

app/views/categoria_do_pagamentos/_form.html.erb
<%= form_for(@categoria_do_pagamento) do |f| %>
	
	<% if @categoria_do_pagamento.errors.any? %>
		<div class="message errormsg" style="display: block; ">
		Não foi possível salvar essa categoria do pagamento</p><br/><br/>
			<% @categoria_do_pagamento.errors.full_messages.each do |msg| %>
			<ul>
			<li><%= msg %></li>
			</ul>
			<% end %>
		</div>
	<% end %>
	
  <div class="field">
    <%= f.label :nome_da_categoria, "Nome" %><br />
    <%= f.text_field :nome_da_categoria, :class => "text small" %>
  </div><br />
   <div class="field">
    <%= f.label :descricao_da_categoria, "Descrição" %><br />
    <%= f.text_field :descricao_da_categoria, :class => "text small" %>
  </div><br />
  <%= f.submit 'Cadastrar', :class => 'submit mid' %>
<% end %>

app/views/categoria_do_pagamentos/edit.html.erb
<div class="block">

	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
	<h1>Editar Categoria do Pagamento</h1>
	</div>

	<div class="block_content">
	<%= render 'form' %>

		<br/>
		<hr>
		<%= link_to 'Show', @categoria_do_pagamento %> |
		<%= link_to 'Back', categoria_do_pagamentos_path %>

	</div>

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>

app/views/categoria_do_pagamentos/index.html.erb
<div class="block">
		<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		<h2>Lista de Categorias de Pagamentos</h2>
		<div class="tableactions" style="text-align: center">
		<%= link_to image_tag('icones/Add.png', :title => "Cadastrar"), new_categoria_do_pagamento_path %>
		</div>
</div>

	<div class="block_content">
		<table cellpadding="0" cellspacing="0" width="100%" class="sortable">

			<tr>
				<th>Nome</th>
				<th>Descrição</th>
			</tr>

			<% @categoria_do_pagamentos.each do |categoria_do_pagamento| %>
			<tr>
				<td><%= categoria_do_pagamento.nome_da_categoria %></td>
				<td><%= categoria_do_pagamento.descricao_da_categoria %></td>
    <td><%= link_to image_tag('icones/Search.png', :title => "Visualizar"), categoria_do_pagamento %></td>
		<td><%= link_to image_tag('icones/Modify.png', :title => "Editar"), edit_categoria_do_pagamento_path(categoria_do_pagamento) %></td>
		<td><%= link_to image_tag('icones/Delete.png', :title => "Deletar"), categoria_do_pagamento, :confirm => 'Are you sure?', :method => :delete %></td>
			</tr>
		<% end %>
		</table>

		<div class="pagination right">
		</div>

	</div>

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>

app/views/categoria_do_pagamentos/new.html.erb
<div class="block">

	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
	<h2>Cadastrar Categoria de Pagamento</h2>
	</div>

  <div class="block_content">
	<%= render 'form' %><br/>
	<hr>
		<p> <%= link_to 'Back', categoria_do_pagamentos_path %></p>
  </div>

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>

app/views/categoria_do_pagamentos/show.html.erb
<div class="block">

	<div class="block_head">
			<div class="bheadl"></div>
			<div class="bheadr"></div>
  <h2>Nome da categoria:<h2>
  <h2>Descrição da categoria:<h2>
  </div>

	<div class="block_content">

	<%= render :partial => '/shared/messages' %>
	<p id="notice">

  <table cellpadding="0" cellspacing="0" width="100%" class="sortable">
		<tr>
			<th>Nome</th>
			<th>Descrição</th>
</tr>

 <td><%= @categoria_do_pagamento.nome_da_categoria %></td>
 <td><%= @categoria_do_pagamento.descricao_da_categoria %></td>

</p>

</table>

		<div class="tableactions">
			<%= link_to 'Edit', edit_pagamento_path(@pagamento) %> |
			<%= link_to 'Back', pagamentos_path %>
		</div>

		<div class="pagination right">

		</div>

	</div>

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>