config/routes.rb
Finance::Application.routes.draw do

  resources :pagamentos

  resources :metodo_de_pagamentos

  resources :categoria_do_pagamentos

  resources :tipo_do_pagamentos

  resources :recebimentos
  
  match "consulta_data", :to => "recebimentos#consulta_data", :as => "consulta_data"

  resources :forma_de_recebimentos

  resources :categoria_do_recebimentos

  resources :tipo_de_recebimentos

  resources :sessions

	match "profile", :to => "users#show", :as => "profile"
	match "logout", :to => "sessions#destroy", :as => "logout"
	match "login", :to => "sessions#new", :as => "login"
	match "admin", :to => "users#admin", :as => "admin"

	resources :users
	

   root :to => "sessions#new"

end

app/models/tipo_de_recebimento.rb
class TipoDeRecebimento < ActiveRecord::Base
	belongs_to :user
	has_many :recebimentos
	
	validates :nome_do_tipo, :presence => true
	validates :descricao_do_tipo, :presence => true
	
end

app/controllers/tipo_de_recebimentos_controller.rb
class TipoDeRecebimentosController < ApplicationController
  # GET /tipo_de_recebimentos
  # GET /tipo_de_recebimentos.xml
  def index
    @tipo_de_recebimentos = TipoDeRecebimento.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tipo_de_recebimentos }
    end
  end

  # GET /tipo_de_recebimentos/1
  # GET /tipo_de_recebimentos/1.xml
  def show
    @tipo_de_recebimento = TipoDeRecebimento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tipo_de_recebimento }
    end
  end

  # GET /tipo_de_recebimentos/new
  # GET /tipo_de_recebimentos/new.xml
  def new
    @tipo_de_recebimento = TipoDeRecebimento.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tipo_de_recebimento }
    end
  end

  # GET /tipo_de_recebimentos/1/edit
  def edit
    @tipo_de_recebimento = TipoDeRecebimento.find(params[:id])
  end

  # POST /tipo_de_recebimentos
  # POST /tipo_de_recebimentos.xml
  def create
   @tipo_de_recebimento = current_user.tipo_de_recebimentos.new(params[:tipo_de_recebimento])
   

    respond_to do |format|
      if @tipo_de_recebimento.save
        format.html { redirect_to(@tipo_de_recebimento, :notice => 'Tipo de recebimento was successfully created.') }
        format.xml  { render :xml => @tipo_de_recebimento, :status => :created, :location => @tipo_de_recebimento }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tipo_de_recebimento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tipo_de_recebimentos/1
  # PUT /tipo_de_recebimentos/1.xml
  def update
    @tipo_de_recebimento = TipoDeRecebimento.find(params[:id])

    respond_to do |format|
      if @tipo_de_recebimento.update_attributes(params[:tipo_de_recebimento])
        format.html { redirect_to(@tipo_de_recebimento, :notice => 'Tipo de recebimento was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tipo_de_recebimento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_de_recebimentos/1
  # DELETE /tipo_de_recebimentos/1.xml
  def destroy
    @tipo_de_recebimento = TipoDeRecebimento.find(params[:id])
    @tipo_de_recebimento.destroy

    respond_to do |format|
      format.html { redirect_to(tipo_de_recebimentos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tipo_de_recebimentos_helper.rb
module TipoDeRecebimentosHelper
end

app/views/tipo_de_recebimentos/_form.html.erb
<%= form_for(@tipo_de_recebimento) do |f| %>

		<% if @tipo_de_recebimento.errors.any? %>
			<div class="message errormsg" style="display: block; ">
				Não foi possível salvar esse tipo de recebimento</p><br/><br/>
				<% @tipo_de_recebimento.errors.full_messages.each do |msg| %>
				<ul>
					<li><%= msg %></li>
				</ul>
				<% end %>
			</div>
		<% end %>


  <div class="field">
    <%= f.label :nome_do_tipo, "Nome" %><br />
    <%= f.text_field :nome_do_tipo, :class => "text small"  %>
  </div><br/>
  <div class="field">
    <%= f.label :descricao_do_tipo, "Descrição" %><br />
    <%= f.text_field :descricao_do_tipo, :class => "text small"  %>
  </div></br>
  
    <%= f.submit 'Cadastrar', :class => 'submit mid' %>
  
<% end %>

app/views/tipo_de_recebimentos/edit.html.erb
<div class="block">

	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		<h2>Editar Tipo do Recebimento</h2>
	</div>

	<div class="block_content">
	<%= render 'form' %>

<br/>
		<hr>
		<%= link_to 'Show', @tipo_de_recebimento %> | <%= link_to 'Back', tipo_de_recebimentos_path %>

	</div>

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>

app/views/tipo_de_recebimentos/index.html.erb
<div class="block">

	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
	<h2>Lista de Tipos de Recebimentos</h2>
		<div class="tableactions" style="text-align: center">
		<%= link_to image_tag('icones/Add.png', :title => "Cadastrar"), new_recebimento_path %>
		</div>
	</div>

<div class="block_content">
	<table cellpadding="0" cellspacing="0" width="100%" class="sortable">
<<<<<<< HEAD

	<div class="tableactions" style="text-align: center">
	<%= link_to image_tag('icones/Add.png', :title => "Cadastrar"), new_tipo_de_recebimento_path %>
	</div>

=======

>>>>>>> d6436b18b8642db983bce50edbbb04b28c02c35d
		<tr>
			<th>Nome</th>
			<th>Descrição</th>
		</tr>

	<% @tipo_de_recebimentos.each do |tipo_de_recebimento| %>
		<tr>
		  <td><%= tipo_de_recebimento.nome_do_tipo %></td>
		  <td><%= tipo_de_recebimento.descricao_do_tipo %></td>


		<td><%= link_to image_tag('icones/Search.png', :title => "Visualizar"), tipo_de_recebimento %></td>
		<td><%= link_to image_tag('icones/Modify.png', :title => "Editar"), edit_tipo_de_recebimento_path(tipo_de_recebimento) %></td>
		<td><%= link_to image_tag('icones/Delete.png', :title => "Deletar"), tipo_de_recebimento, :confirm => 'Are you sure?', :method => :delete %></td>

		</tr>

	<% end %>
	</table>

	<div class="pagination right">

	</div>

</div>

<div class="bendl"></div>
	<div class="bendr"></div>

	</div>

app/views/tipo_de_recebimentos/new.html.erb
<div class="block">

	<div class="block_head">
		<div class="bheadl"></div>
		<div class="bheadr"></div>
		<h2>Cadastrar Tipo do Recebimento</h2>
	</div>

	<div class="block_content">
	<%= render 'form' %>

<br/>
		<hr>
		<%= link_to 'Back', tipo_de_recebimentos_path %>

	</div>

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>

app/views/tipo_de_recebimentos/show.html.erb
<div class="block">

	<div class="block_head">
			<div class="bheadl"></div>
			<div class="bheadr"></div>

	<h2>Resumo do Recebimento</h2>
	</div>

	<div class="block_content">

	<%= render :partial => '/shared/messages' %>
	<p id="notice">

	<table cellpadding="0" cellspacing="0" width="100%" class="sortable">

	<tr>
		<th>Nome</th>
		<th>Descrição</th>
	</tr>

	<tr>
		<td><%= @tipo_de_recebimento.nome_do_tipo %></td>
		<td><%= @tipo_de_recebimento.descricao_do_tipo %></td>
	</tr>
</table>

<div class="tableactions">
			<%= link_to 'Edit', edit_tipo_de_recebimento_path(@tipo_de_recebimento) %> |
			<%= link_to 'Back', tipo_de_recebimentos_path %>
		</div>

		<div class="pagination right">

		</div>

	</div>

	<div class="bendl"></div>
	<div class="bendr"></div>

</div>